djangonutic/QandA/urls.py
from django.urls import path
from . import views

app_name = "QandA"

urlpatterns = [
    path('', views.QandA_list, name="list"),
]

djangonutic/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"


urlpatterns = [
    path("login/", views.account_login, name="login"),
    path("logout/", views.account_logout, name="logout"),
]

djangonutic/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail, name="detail"),

]

djangonutic/contact/urls.py
from django.urls import path
from . import views

app_name = "contact"

urlpatterns = [
    path('', views.contact_create_list, name="create_list"),
    # path('thank-you/', views.contact_thank_you, name="thank_you"),
    path('view_list', views.contact_view_list, name="view_list"),
    path('<slug:slug>/', views.contact_view_detail, name="view_detail"),
]

djangonutic/djangonutic/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from gaiyou import views as gaiyou_views
from shoukai import views as shoukai_views
from QandA import views as QandA_views
from contact import views as contact_veiws
from privacy import views as privacy_views
from home import views as home_views

urlpatterns = [
    path('', home_views.home_list),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('articles/', include("articles.urls")),
    path('gaiyou/', include("gaiyou.urls")),
    path('shoukai/', include("shoukai.urls")),
    path('qanda/', include("QandA.urls")),
    path('contact/', include("contact.urls")),
    path('privacy/', include("privacy.urls")),
    path('home/', include("home.urls")),
    path('recruitment/', include("recruitment.urls")),
    path('about/', views.about),
    path('404/', views.view_404),
    path('manifest.json', views.view_manifest_json),
    path('robots.txt', views.view_robot_txt),
    # path('', views.homepage),
    # path('', include("articles.urls")),



]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonutic/gaiyou/urls.py
from django.urls import path
from . import views

app_name = "gaiyou"

urlpatterns = [
    path('', views.gaiyou_list, name="list"),
    path('map/', views.gaiyou_map, name="map")
]

djangonutic/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home_list, name="list"),
]

djangonutic/privacy/urls.py
from django.urls import path
from . import views

app_name = "privacy"

urlpatterns = [
    path('', views.privacy_list, name="list"),
]

djangonutic/recruitment/urls.py
from django.urls import path
from . import views

app_name = "recruitment"

urlpatterns = [
    path('', views.recruitment_list, name="list"),
]

djangonutic/shoukai/urls.py
from django.urls import path
from . import views

app_name = "shoukai"

urlpatterns = [
    path('', views.shoukai_list, name="list"),
]

djangonutic/QandA/models.py
from django.db import models

# Create your models here.

djangonutic/contact/models.py
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    email = models.EmailField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name if self.name else self.body if self.body else self.email if self.email else str(self.date)

    def snippet(self):
        return self.body if len(self.body) < 20 else self.body[:10] + " • • •"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.email)
        super(Contact, self).save(*args, **kwargs)

djangonutic/gaiyou/models.py
from django.db import models

# Create your models here.

djangonutic/home/models.py
from django.db import models

# Create your models here.

djangonutic/QandA/views.py
from django.shortcuts import render

# Create your views here.


def QandA_list(request):
    return render(request, "QandA/QandA_list.html")

djangonutic/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.

def account_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if "next" in request.POST:
                print("[***?next=] ", request.POST.get("next"))
                return redirect(request.POST.get("next"))
            else:
                # print(request.read())
                return redirect("articles:list")
    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html", {"form": form})


def account_logout(request):
    if request.method == "POST":
        logout(request)
        return redirect("articles:list")

djangonutic/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import model_forms
# Create your views here.


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == "POST":
        #                                   files dont come with POST so ...
        form = model_forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect("articles:list")
    else:

        form = model_forms.CreateArticle()
    return render(request, "articles/article_creat.html", {"form": form})


def article_list(request):

    articles = Article.objects.all().order_by("date")
    return render(request, "articles/article_list.html", {"articles": articles})


def article_detail(requeat, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(requeat, "articles/article_detail.html", {"article": article})

djangonutic/contact/views.py
from django.shortcuts import render, redirect
from . import model_forms
from .models import Contact
# Create your views here.


def contact_view_list(request):
    contacts = Contact.objects.all().order_by("date")
    return render(request, "contact/contact_view_list.html", {"contacts": contacts})


def contact_view_detail(requeat, slug):
    # return HttpResponse(slug)
    contact = Contact.objects.get(slug=slug)
    return render(requeat, "contact/contact_view_detail.html", {"contact": contact})


def contact_create_list(request):
    if request.method == "POST":
        form = model_forms.CreateContact(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "contact/contact_thank_you.html")
    else:
        form = model_forms.CreateContact()
    return render(request, "contact/contact_create_list.html", {"form": form})


# def contact_thank_you(request):
#     return render(request, "contact/contact_thank_you.html")

djangonutic/gaiyou/views.py
from django.shortcuts import render

# Create your views here.


def gaiyou_list(request):

    return render(request, "gaiyou/gaiyou_list.html")


def gaiyou_map(request):
    return render(request, "gaiyou/gaiyou_map.html")

djangonutic/home/views.py
from django.shortcuts import render


def home_list(request):
    return render(request, "home/home_list.html")

djangonutic/privacy/views.py
from django.shortcuts import render

# Create your views here.


def privacy_list(request):
    return render(request, "privacy/privacy_list.html")

djangonutic/shoukai/views.py
from django.shortcuts import render

# Create your views here.


def shoukai_list(request):
    return render(request, "shoukai/shoukai_list.html")

djangonutic/templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>about</title>
</head>

<body>
    <h1>this is <big>about</big> page</h1>
</body>

</html>

djangonutic/templates/base_layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="canonicalize" href="https://zainsyed.pythonanywhere.com/">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="有限会社新富士(shinfuji co.,ltd)は輸出輸入を主に行う会社です。世界中に日本の技術、文化、歴史、を届ける輸出輸入専門の会社です。">
    <meta name="author" content="有限会社新富士">
    <meta name="keywords" content="有限会社新富士,輸出輸入,shinfuji,shinfuji co ltd">

    <!-- bad way of calling static files -->
    <!-- <link rel="stylesheet" href="/static/styles.css"> -->
    <link rel="stylesheet" href="{%static 'styles.css'%}">
    <link rel="shortcut icon" type="image/png" href="" />
    <link rel="icon" type="image/x-icon" href="{%static 'logo.ico'%}">
    <title>有限会社新富士 | 輸出輸入 | shinfuji co ltd | shinfuji | 新富士 </title>
    <!--shinfuji co ltd-->
    <!--有限会社　新富士-->
    <!--代表者 ダストギール セイエド グラーム-->
</head>

<body>
    <div class="wrepper">
        <header>
            <h2><a href="{% url 'home:list'%}"><img title=“有限会社新富士(shinfuji co.,ltd)” alt="有限会社新富士(shinfuji co.,ltd)"
                        src="{%static 'logo.png'%}"></a></h2>

            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{%url 'accounts:logout'%}" method="post">
                            {% csrf_token %}
                            <button type="submit">LogOut</button>
                        </form>
                    </li>
                    <li>
                        <a href="{%url 'articles:create'%}" class="highlight">New Article</a>
                    </li>
                    <li>
                        <a href="{%url 'contact:view_list'%}" class="highlight">View Contact</a>
                    </li>
                    {% else %}
                    <li>
                        <a href="{%url 'accounts:login'%}">LogIn</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>

        </header>

        <!-- on big screan -->
        <button class="menu">☰</button>

        <nav class="banner">
            <ul>
                <a href="{% url 'home:list' %}">
                    <li>ホーム</li>
                </a>
                <a href="{% url 'gaiyou:list' %}">
                    <li>会社概要</li>
                </a>
                <a href="{% url 'shoukai:list' %}">
                    <li>事業紹介</li>
                </a>
                <a href="{% url 'articles:list' %}">
                    <li>事例紹介</li>
                </a>
                <a href="{% url 'QandA:list' %}">
                    <li>ご質問</li>
                </a>
                <a href="{% url 'contact:create_list' %}">
                    <li>お問い合わせ</li>
                </a>
                <a href="{% url 'privacy:list' %}">
                    <li>プライバシーポリシ</li>
                </a>
                <a href="{% url 'recruitment:list' %}">
                    <li>採用情報</li>
                </a>
            </ul>
        </nav>







        {% block content %}

        {% endblock content %}
    </div>
    <script src="{%static 'app.js'%}"></script>
</body>

</html>

djangonutic/templates/homepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>home</title>
</head>

<body>
    <h1>this is <big>homepage</big> ,page...</h1>
</body>

</html>