djangonutic/QandA/urls.py
from django.urls import path
from . import views

app_name = "QandA"

urlpatterns = [
    path('', views.QandA_list, name="list"),
]

djangonutic/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"


urlpatterns = [
    path("login/", views.account_login, name="login"),
    path("logout/", views.account_logout, name="logout"),
]

djangonutic/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail, name="detail"),

]

djangonutic/contact/urls.py
from django.urls import path
from . import views

app_name = "contact"

urlpatterns = [
    path('', views.contact_create_list, name="create_list"),
    # path('thank-you/', views.contact_thank_you, name="thank_you"),
    path('view_list', views.contact_view_list, name="view_list"),
    path('<slug:slug>/', views.contact_view_detail, name="view_detail"),
]

djangonutic/djangonutic/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from gaiyou import views as gaiyou_views
from shoukai import views as shoukai_views
from QandA import views as QandA_views
from contact import views as contact_veiws
from privacy import views as privacy_views
from home import views as home_views

urlpatterns = [
    path('', home_views.home_list),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('articles/', include("articles.urls")),
    path('gaiyou/', include("gaiyou.urls")),
    path('shoukai/', include("shoukai.urls")),
    path('qanda/', include("QandA.urls")),
    path('contact/', include("contact.urls")),
    path('privacy/', include("privacy.urls")),
    path('home/', include("home.urls")),
    path('recruitment/', include("recruitment.urls")),
    path('about/', views.about),
    path('404/', views.view_404),
    path('manifest.json', views.view_manifest_json),
    path('robots.txt', views.view_robot_txt),
    # path('', views.homepage),
    # path('', include("articles.urls")),



]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonutic/gaiyou/urls.py
from django.urls import path
from . import views

app_name = "gaiyou"

urlpatterns = [
    path('', views.gaiyou_list, name="list"),
    path('map/', views.gaiyou_map, name="map")
]

djangonutic/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home_list, name="list"),
]

djangonutic/privacy/urls.py
from django.urls import path
from . import views

app_name = "privacy"

urlpatterns = [
    path('', views.privacy_list, name="list"),
]

djangonutic/recruitment/urls.py
from django.urls import path
from . import views

app_name = "recruitment"

urlpatterns = [
    path('', views.recruitment_list, name="list"),
]

djangonutic/shoukai/urls.py
from django.urls import path
from . import views

app_name = "shoukai"

urlpatterns = [
    path('', views.shoukai_list, name="list"),
]

djangonutic/QandA/models.py
from django.db import models

# Create your models here.

djangonutic/accounts/models.py
from django.db import models

# Create your models here.

djangonutic/contact/models.py
from django.db import models
from django.template.defaultfilters import slugify

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    email = models.EmailField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name if self.name else self.body if self.body else self.email if self.email else str(self.date)

    def snippet(self):
        return self.body if len(self.body) < 20 else self.body[:10] + " • • •"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.email)
        super(Contact, self).save(*args, **kwargs)

djangonutic/gaiyou/models.py
from django.db import models

# Create your models here.

djangonutic/home/models.py
from django.db import models

# Create your models here.

djangonutic/privacy/models.py
from django.db import models

# Create your models here.

djangonutic/shoukai/models.py
from django.db import models

# Create your models here.

djangonutic/QandA/views.py
from django.shortcuts import render

# Create your views here.


def QandA_list(request):
    return render(request, "QandA/QandA_list.html")

djangonutic/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.

def account_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if "next" in request.POST:
                print("[***?next=] ", request.POST.get("next"))
                return redirect(request.POST.get("next"))
            else:
                # print(request.read())
                return redirect("articles:list")
    else:
        form = AuthenticationForm()
    return render(request, "accounts/login.html", {"form": form})


def account_logout(request):
    if request.method == "POST":
        logout(request)
        return redirect("articles:list")

djangonutic/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import model_forms
# Create your views here.


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == "POST":
        #                                   files dont come with POST so ...
        form = model_forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect("articles:list")
    else:

        form = model_forms.CreateArticle()
    return render(request, "articles/article_creat.html", {"form": form})


def article_list(request):

    articles = Article.objects.all().order_by("date")
    return render(request, "articles/article_list.html", {"articles": articles})


def article_detail(requeat, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(requeat, "articles/article_detail.html", {"article": article})

djangonutic/contact/views.py
from django.shortcuts import render, redirect
from . import model_forms
from .models import Contact
# Create your views here.


def contact_view_list(request):
    contacts = Contact.objects.all().order_by("date")
    return render(request, "contact/contact_view_list.html", {"contacts": contacts})


def contact_view_detail(requeat, slug):
    # return HttpResponse(slug)
    contact = Contact.objects.get(slug=slug)
    return render(requeat, "contact/contact_view_detail.html", {"contact": contact})


def contact_create_list(request):
    if request.method == "POST":
        form = model_forms.CreateContact(request.POST)
        if form.is_valid():
            form.save()
            return render(request, "contact/contact_thank_you.html")
    else:
        form = model_forms.CreateContact()
    return render(request, "contact/contact_create_list.html", {"form": form})


# def contact_thank_you(request):
#     return render(request, "contact/contact_thank_you.html")

djangonutic/gaiyou/views.py
from django.shortcuts import render

# Create your views here.


def gaiyou_list(request):

    return render(request, "gaiyou/gaiyou_list.html")


def gaiyou_map(request):
    return render(request, "gaiyou/gaiyou_map.html")

djangonutic/home/views.py
from django.shortcuts import render


def home_list(request):
    return render(request, "home/home_list.html")

djangonutic/privacy/views.py
from django.shortcuts import render

# Create your views here.


def privacy_list(request):
    return render(request, "privacy/privacy_list.html")

djangonutic/shoukai/views.py
from django.shortcuts import render

# Create your views here.


def shoukai_list(request):
    return render(request, "shoukai/shoukai_list.html")

djangonutic/QandA/templates/QandA/QandA_list.html
{% extends 'base_layout.html' %}

{% block content %}
<div>
    <div>
        <h1 class="QandA_dig_QA">Q</h1>
        <p class="QandA_Q_p">how much is one contener</p>
        <h1 class="QandA_big_QA">A</h1>
        <p class="QandA_A_p">it is about 200万円</p>    
    </div>
        <div>
        <h1 class="QandA_dig_QA">Q</h1>
        <p class="QandA_Q_p">how much is two contener</p>
        <h1 class="QandA_big_QA">A</h1>
        <p class="QandA_A_p">it is about 400万円</p>    
    </div>
        <div>
        <h1 class="QandA_dig_QA">Q</h1>
        <p class="QandA_Q_p">how much is thiree contener</p>
        <h1 class="QandA_big_QA">A</h1>
        <p class="QandA_A_p">it is about 600万円</p>    
    </div>

</div>

{% endblock content %}

djangonutic/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="creat-article">
    <div><big>LOGIN</big></div>
    <form class='site-form' action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}

        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}

        <input type="submit" value="LogIn">
    </form>
</div>

{% endblock content %}

djangonutic/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

<h1>signup</h1>

<form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="SignUp">
</form>

{% endblock content %}

djangonutic/contact/templates/contact/contact_create_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="creat-article">
        <h2>お問い合わせ</h2>
        <form class="site-form"action="{% url 'contact:create_list' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Create">
        </form>
    </div>

{% endblock content %}

djangonutic/contact/templates/contact/contact_thank_you.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Thank you for contacting us!</h1>
{% endblock content %}

djangonutic/contact/templates/contact/contact_view_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article_detail">
    <div class="article">
        <h2>{{ contact.name }}</h2>
        <p>{{ contact.email}}</p>
        <p>{{contact.body }}</p>
        <p>{{contact.date }}</p>
    </div>
</div>

{% endblock content %}

djangonutic/contact/templates/contact/contact_view_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>contcts</h1>
<div class="articles">
    {% for contact in contacts%}
    <a href="{% url 'contact:view_detail' slug=contact.slug %}">
        <div class="article">
            <h2>{{contact.name}}</h2>
            <p>{{contact.snippet}}</p>
            <h5>{{contact.date}}</h5>
        </div>
    </a>
    {% endfor%}
</div>
{% endblock content %}

djangonutic/gaiyou/templates/gaiyou/gaiyou_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>会社概要</h1>
<div class="gaiyou">
    <table>
    <tr class = "gaiyou_1">
        <td class="side">会社名</td>
        <td>新富士</td>
    </tr>
    <tr class="gaiyou_2">
        <td class="side">代表者</td>
        <td>ダスタギール　セイエド　グラーム</td>
    </tr>
    <tr class="gaiyou_1">
        <td class="side">所在地</td>
        <td>埼玉県越谷市  <a href="{% url 'gaiyou:map' %}"><span>地図</span></a></td>
    </tr>
    <tr class="gaiyou_2">
        <td class="side">電話番号</td>
        <td>080 3127 9781</td>
    </tr>
    <tr class="gaiyou_1">
        <td class="side">設立</td>
        <td>2005年01月01日</td>
    </tr>
    <tr class="gaiyou_2">
        <td class="side">事業内容</td>
        <td>輸出入</td>
    </tr>
    <tr class="gaiyou_1">
        <td class="side">資本金</td>
        <td>2500万</td>
    </tr>
    <tr class="gaiyou_2">
        <td class="side">従業員数</td>
        <td>1000人</td>
    </tr>
    <tr class="gaiyou_1">
        <td class="side">主要取引先</td>
        <td>日本輸出入協会</td>
    </tr>
    <tr class="gaiyou_2">
        <td class="side">取引銀行</td>
        <td>三井住友銀行　、関東銀行</td>
    </tr>
    </table>

</div>
{% endblock content %}

djangonutic/gaiyou/templates/gaiyou/gaiyou_map.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>会社　地図</h1>
<div class="map">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3771.8156962956805!2d139.79053081689037!3d35.88859270277367!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6018966f721e31f3%3A0x634bd12a0c476e2b!2sKOSHIGAYA%20STATION!5e0!3m2!1sen!2sjp!4v1620570795942!5m2!1sen!2sjp" width="1000" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</div>
{% endblock content %}

djangonutic/privacy/templates/privacy/privacy_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>privacy</h1>
<div class="privacy">
<p>we will protect your data.</p>
</div>
{% endblock content %}

djangonutic/shoukai/templates/shoukai/gaiyou_map.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>会社　地図</h1>
<div class="map">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3771.8156962956805!2d139.79053081689037!3d35.88859270277367!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6018966f721e31f3%3A0x634bd12a0c476e2b!2sKOSHIGAYA%20STATION!5e0!3m2!1sen!2sjp!4v1620570795942!5m2!1sen!2sjp" width="1000" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</div>
{% endblock content %}

djangonutic/shoukai/templates/shoukai/shoukai_list.html
{% extends 'base_layout.html' %}

{% block content %}
{% load static %}
<h1>企業紹介</h1>
<div class="shoukai">
    <div>
        <p class="shoukai_main_p">我々は「GO, NEXT
            STAGE」を掲げ社員一人一人が自らの役割を認識し持てる能力を駆使し創造性を発揮して新たなビジネスチャンスに挑みます。自己実現に向けて「変革・挑戦・創造する」人材の集合体です。</p>
        <img class="shoukai_main_img" src="{% static 'shoukai_main.jpg' %}">
    </div>
    <div>
        <img class="shoukai_sec_main_img" src="{% static 'shoukai_sec_main.png' %}">
        <h2 class="seo-word">イノベーションに必要な<br>あらゆる人材サービスを提供できる存在に</h2>
        <div class="shoukai_sec_main_p">
            <br>
            <p>「昔はね、自動車はお店で買って、自分で運転するものだったんだよ」自分の子供や孫たちにこんな説明をする日も、そう遠くはないかもしれません。</p>
            <br>
            <p>20世紀最大の発明のひとつである自動車産業では、世界の名だたる自動車メーカーが自分たちのビジネスを「自動車製造」から「モビリティサービス・プラットフォーム」へ変化させようとしています。FinTechの発達により、中国では道端の屋台でさえ電子決済が可能となりました。エストニアのように国全体で行政手続が電子化された国家も出現しています。
            </p>
            <br>
            <p>もはやITなくしては生活や仕事は成り立ちません。それらITの維持・発展を支えるのが、ITエンジニアであり、ITを活用して世に新しい価値を提供する企業なのです。そのITエンジニアと企業を支援することで、これからも世にイノベーションを起こし続ける。これが我々アイムファクトリーのミッションです。
            </p>
            <br>
            <p>テクノロジーの進化は日々急速に進みます。それに伴いITエンジニアの働き方やキャリアデザインも急速に変化し、ITエンジニアを必要とする企業の状況も刻々と変わり続けます。イノベーションに関わるすべての人と企業を支援するために、私たち自身もIT領域の最先端に立ち常に挑戦し、変化し続けることで、イノベーションに必要なあらゆる人材サービスを提供できる存在に成長していきたいと考えています。
            </p>
            <br>
            <p>代表取締役 ダスタギール　セイエド　グラーム</p>
        </div>

    </div>

</div>
{% endblock content %}