djangonutic/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('<slug:slug>/', views.article_detail, name="detail"),

]

djangonutic/djangonutic/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from gaiyou import views as gaiyou_views
from shoukai import views as shoukai_views
from QandA import views as QandA_views
from contact import views as contact_veiws
from privacy import views as privacy_views
from home import views as home_views

urlpatterns = [
    path('', home_views.home_list),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('articles/', include("articles.urls")),
    path('gaiyou/', include("gaiyou.urls")),
    path('shoukai/', include("shoukai.urls")),
    path('qanda/', include("QandA.urls")),
    path('contact/', include("contact.urls")),
    path('privacy/', include("privacy.urls")),
    path('home/', include("home.urls")),
    path('recruitment/', include("recruitment.urls")),
    path('about/', views.about),
    path('404/', views.view_404),
    path('manifest.json', views.view_manifest_json),
    path('robots.txt', views.view_robot_txt),
    # path('', views.homepage),
    # path('', include("articles.urls")),



]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonutic/home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home_list, name="list"),
]

djangonutic/articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    # add in thumbnali later
    thumb = models.ImageField(default='default.png', blank=True)
    # add in Auther alter
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE,)

    # in ""Article.objects.all()""  outputs ==>  ""<QuerySet [<Article: Article object (1)>]>""
    # to make it easy to see we change the __str__ func
    # this function returns the str of this hole objec as ""nameofobject object"" so we change it

    def __str__(self):

        return self.title if self.title else self.body if self.body else self.slug if self.slug else str(self.date)

    def snippet(self):
        return self.body if len(self.body) < 20 else self.body[:20] + " • • •"

# this makes the file witch contains these upper things in a nice format
    # python manage.py makemigrations       prep of migration
# this migrates that file to database
    # python manage.py migrate              doing migration to db

djangonutic/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import model_forms
# Create your views here.


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == "POST":
        #                                   files dont come with POST so ...
        form = model_forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect("articles:list")
    else:

        form = model_forms.CreateArticle()
    return render(request, "articles/article_creat.html", {"form": form})


def article_list(request):

    articles = Article.objects.all().order_by("date")
    return render(request, "articles/article_list.html", {"articles": articles})


def article_detail(requeat, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(requeat, "articles/article_detail.html", {"article": article})

djangonutic/articles/templates/articles/article_creat.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="creat-article">
        <h2>Creat a great article</h2>
        <form class="site-form"action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Create">
        </form>
    </div>

{% endblock content %}

djangonutic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article_detail">
    <div class="article">
        <img src="{{article.thumb.url}}">
        <h2>{{ article.title }}</h2>
        <p>{{article.body }}</p>
        <p>{{article.date }}</p>
    </div>
</div>

{% endblock content %}

djangonutic/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>事例・実績紹介</h1>
<div class="articles">
    {% for article in articles%}
    <a href="{% url 'articles:detail' slug=article.slug %}">
        <div class="article">
            <h2>{{article.title}}</h2>
            <img class = "article_imgs"src="{{article.thumb.url}}">
            <p>{{article.snippet}}</p>
            <h5>{{article.date}}</h5>
            <h5 class="author">added by {{article.author.username}}</h5>
        </div>
    </a>
    {% endfor%}
</div>
{% endblock content %}